from .fedavg import FederatedAverage
from .bayesian import FederatedBayesian
from .bulyan import FederatedBulyan
from .bucketing import FederatedBucketing
from .krum import FederatedKrum
from .median import FederatedMedian
from .trimmedavg import FederatedTrimmedAverage
from .geomed import FederatedGeometricMedian
from .mixing import FederatedMixing